#!/bin/bash

echo "=== Apply Nginx Configuration for PHP 8.3 ==="
echo ""
echo "PHP 8.3 is installed and running."
echo "PHP-FPM socket: /var/run/php/php8.3-fpm.sock"
echo ""
echo "To enable PHP processing for port 1112, run these commands:"
echo ""
echo "1. Copy the nginx configuration:"
echo "   sudo cp nginx-php-config.conf /etc/nginx/sites-available/project1-php"
echo ""
echo "2. Enable the site:"
echo "   sudo ln -s /etc/nginx/sites-available/project1-php /etc/nginx/sites-enabled/"
echo ""
echo "3. Remove any conflicting default site:"
echo "   sudo rm /etc/nginx/sites-enabled/default"
echo ""
echo "4. Test nginx configuration:"
echo "   sudo nginx -t"
echo ""
echo "5. Reload nginx:"
echo "   sudo systemctl reload nginx"
echo ""
echo "6. Set proper permissions:"
echo "   sudo chown -R www-data:www-data /home/successbank/projects/docker/project1/html"
echo "   sudo chmod -R 755 /home/successbank/projects/docker/project1/html"
echo ""
echo "7. Test PHP:"
echo "   curl http://211.248.112.67:1112/test.php"
echo "   curl http://211.248.112.67:1112/phpinfo.php"
echo ""
echo "If port 1112 is already configured elsewhere, you need to find and update that config file."
echo "Check with: sudo grep -r 'listen.*1112' /etc/nginx/"