#!/usr/bin/env php
<?php
/**
 * Database Backup Script
 * Backs up project1_db to backups directory
 */

$backup_dir = '/home/successbank/projects/docker/project1/backups';
$timestamp = date('Y-m-d_His');
$backup_file = "{$backup_dir}/project1_db_backup_{$timestamp}.sql";

try {
    $pdo = new PDO('mysql:host=127.0.0.1;dbname=project1_db;charset=utf8mb4', 'root', 'rootpassword');
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

    echo "=== Database Backup Started ===\n";
    echo "Database: project1_db\n";
    echo "Backup file: $backup_file\n\n";

    // Open backup file
    $fp = fopen($backup_file, 'w');
    if (!$fp) {
        throw new Exception("Cannot create backup file: $backup_file");
    }

    // Write header
    fwrite($fp, "-- Database Backup: project1_db\n");
    fwrite($fp, "-- Date: " . date('Y-m-d H:i:s') . "\n");
    fwrite($fp, "-- Generated by: backup_db.php\n\n");
    fwrite($fp, "SET FOREIGN_KEY_CHECKS=0;\n\n");

    // Get all tables
    $stmt = $pdo->query("SHOW TABLES");
    $tables = $stmt->fetchAll(PDO::FETCH_COLUMN);

    echo "Found " . count($tables) . " tables to backup:\n";

    foreach ($tables as $table) {
        echo "  - Backing up table: $table... ";

        // Get CREATE TABLE statement
        $create_stmt = $pdo->query("SHOW CREATE TABLE `$table`")->fetch(PDO::FETCH_ASSOC);
        fwrite($fp, "\n-- Table structure for `$table`\n");
        fwrite($fp, "DROP TABLE IF EXISTS `$table`;\n");
        fwrite($fp, $create_stmt['Create Table'] . ";\n\n");

        // Get table data
        $data_stmt = $pdo->query("SELECT * FROM `$table`");
        $row_count = 0;

        fwrite($fp, "-- Data for table `$table`\n");

        while ($row = $data_stmt->fetch(PDO::FETCH_ASSOC)) {
            if ($row_count == 0) {
                fwrite($fp, "INSERT INTO `$table` (");
                fwrite($fp, implode(', ', array_map(function($col) { return "`$col`"; }, array_keys($row))));
                fwrite($fp, ") VALUES\n");
            } else {
                fwrite($fp, ",\n");
            }

            $values = array_map(function($val) use ($pdo) {
                if ($val === null) return 'NULL';
                return $pdo->quote($val);
            }, array_values($row));

            fwrite($fp, "(" . implode(', ', $values) . ")");
            $row_count++;
        }

        if ($row_count > 0) {
            fwrite($fp, ";\n\n");
        }

        echo "$row_count rows\n";
    }

    fwrite($fp, "SET FOREIGN_KEY_CHECKS=1;\n");
    fclose($fp);

    // Get file size
    $file_size = filesize($backup_file);
    $size_mb = round($file_size / 1024 / 1024, 2);

    echo "\n=== Backup Complete ===\n";
    echo "Backup file: $backup_file\n";
    echo "File size: {$size_mb} MB ({$file_size} bytes)\n";

    // List recent backups
    echo "\n=== Recent Backups ===\n";
    $backups = glob("{$backup_dir}/project1_db_backup_*.sql");
    rsort($backups);
    $recent = array_slice($backups, 0, 5);
    foreach ($recent as $backup) {
        $size = filesize($backup);
        $size_mb = round($size / 1024 / 1024, 2);
        $date = date('Y-m-d H:i:s', filemtime($backup));
        echo "  " . basename($backup) . " - {$size_mb} MB - $date\n";
    }

} catch (Exception $e) {
    echo "Error: " . $e->getMessage() . "\n";
    exit(1);
}
?>