#!/bin/bash

echo "=== PHP Installation Script ==="
echo ""
echo "This script will guide you through installing PHP-FPM for nginx"
echo ""
echo "Please run the following commands with sudo:"
echo ""
echo "# Update package list"
echo "sudo apt update"
echo ""
echo "# Install PHP and required packages"
echo "sudo apt install -y php-fpm php-mysql php-common php-cli php-curl php-mbstring php-xml"
echo ""
echo "# Check PHP version"
echo "php -v"
echo ""
echo "# Find PHP-FPM socket"
echo "ls -la /var/run/php/"
echo ""
echo "# Start PHP-FPM service"
echo "sudo systemctl start php*-fpm"
echo "sudo systemctl enable php*-fpm"
echo ""
echo "After installation, run ./configure-nginx.sh to set up nginx"