#!/bin/bash

echo "=== PHP Setup Instructions for nginx ==="
echo ""
echo "The issue: PHP files are being downloaded instead of executed."
echo "This means nginx is not configured to process PHP files."
echo ""
echo "To fix this, you need to:"
echo ""
echo "1. Install PHP and PHP-FPM:"
echo "   sudo apt update"
echo "   sudo apt install php-fpm php-mysql php-common"
echo ""
echo "2. Check PHP-FPM version and socket:"
echo "   ls /var/run/php/"
echo "   (Look for something like php8.0-fpm.sock)"
echo ""
echo "3. Configure nginx to handle PHP:"
echo "   Edit your nginx configuration file for port 1112"
echo "   Add the following location block:"
echo ""
echo "location ~ \.php$ {"
echo "    include snippets/fastcgi-php.conf;"
echo "    fastcgi_pass unix:/var/run/php/php8.0-fpm.sock;"
echo "}"
echo ""
echo "4. Ensure index.php is in the index directive:"
echo "   index index.php index.html index.htm;"
echo ""
echo "5. Test and reload nginx:"
echo "   sudo nginx -t"
echo "   sudo systemctl reload nginx"
echo ""
echo "6. Test PHP:"
echo "   curl http://211.248.112.67:1112/test.php"
echo ""
echo "Alternative: If using Docker, ensure PHP-FPM is installed in the container"
echo "and properly linked to nginx."