#!/bin/bash

echo "=== Roundcube UI 확인을 위한 간단한 IMAP 서버 설치 ==="
echo ""
echo "아래 명령어를 실행하면 테스트용 IMAP 서버가 설치됩니다:"
echo ""
echo "docker run -d \\"
echo "  --name dovecot \\"
echo "  -p 143:143 \\"
echo "  -e MAIL_USER=demo@example.com \\"
echo "  -e MAIL_PASS=demo \\"
echo "  dovecot/dovecot"
echo ""
echo "또는 더 간단한 테스트 서버:"
echo ""
echo "docker run -d \\"
echo "  --name test-imap \\"
echo "  -p 143:143 \\"
echo "  -e MAIL_ACCOUNTS=demo@example.com:demo \\"
echo "  tvial/docker-mailserver:latest"
echo ""
echo "설치 후 Roundcube에서 demo@example.com / demo 로 로그인하세요."